# Script to auto-generate PTR XML files for LUCID


# Functions to input and validate data
def get_datetime(prompt):
    datetime = ""
    while (datetime == ""):
        print prompt
        try:
            year = str(int(raw_input("Year: "))).zfill(2)
            month = str(int(raw_input("Month: "))).zfill(2)
            day = str(int(raw_input("Day: "))).zfill(2)
            hour = str(int(raw_input("Hour: "))).zfill(2)
            minute = str(int(raw_input("Minute: "))).zfill(2)
            second = str(int(raw_input("Second: "))).zfill(2)

            # Format date / time
            datetime = year+"-"+month+"-"+day+"T"+hour+":"+minute+":"+second

            return datetime
        
        except ValueError:
            print "Invalid input"

        except SyntaxError:
            print "Invalid input"

def get_duration(prompt):    
    dur = ""
    while (dur == ""):
        print prompt
        try:
            day = str(int(raw_input("Day: "))).zfill(2)
            hour = str(int(raw_input("Hour: "))).zfill(2)
            minute = str(int(raw_input("Minute: "))).zfill(2)
            second = str(int(raw_input("Second: "))).zfill(2)

            # Format duration
            dur = day+"T"+hour+":"+minute+":"+second

            return dur
        
        except ValueError:
            print "Invalid input"

        except SyntaxError:
            print "Invaid input"
        

pref_start_time = get_datetime("\nEnter preferred Start Time")
earliest_start_time = get_datetime("\nEnter earliest Start Time")
latest_start_time = get_datetime("\nEnter latest Start Time")

duration = get_duration("\nEnter duration")

ptr_id = raw_input("\nEnter PTR ID ")

priority = str(0)
priority = raw_input("Enter priority (1 for low priority, 2 for medium priority, 3 for high priority): ")

explan_text = ""
explan_text = raw_input("Enter explanatory text (optional): ")


# Generate XML file from inputted data

xml = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ptrFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PtrFile.xsd">
    <fileHeader>
        <source>ReSI payload provider</source>	
        <destination>MPS</destination>	
        <issueDate>202014-03-03T18:31:48</issueDate>		
        <information>Generated by ...</information>			
    </fileHeader>
    <ptrFileId>"""+str(ptr_id)+"""</ptrFileId>	
        <ptr>
        <domain>TDS-1</domain>
        <ptrId>"""+str(ptr_id)+"""</ptrId>
        <preferredStartTime>"""+pref_start_time+"""</preferredStartTime>
        <earliestStartTime>"""+earliest_start_time+"""</earliestStartTime>
        <latestStartTime>"""+latest_start_time+"""</latestStartTime>
        <duration>"""+duration+"""</duration>
        <taskPriority>"""+priority+"""</taskPriority>
        <explanatoryText>"""+explan_text+"""</explanatoryText>
        <TASK_LUCID_DATA/>	
    </ptr>
</ptrFile>

"""

filename = raw_input("\nEnter filename to be written to: ")

outfile = open(filename + ".ptr", "w")
outfile.write(xml)
outfile.close()

print "\nDone"

            
