# Script to generate PTR files using command line arguments, takes 25 inputs

import sys

# From original script, formatting functions

def format_datetime(year, month, day, hour, minute, second):
	# Format date / time
    datetime = year+"-"+month+"-"+day+"T"+hour+":"+minute+":"+second
    return datetime
	
def format_duration(day, hour, minute, second):
	dur = day+"T"+hour+":"+minute+":"+second
	return dur

# Check for correct number of command line arguments

def usage():
	print "An incorrect number of command line arguments were provided to the program. Cannot continue. \n"

if ((len(sys.argv) - 1) != 25):
	#Incorrect number of arguments
	usage()
	
else:
	
	# Read command line arguments and store into variables

	pref_start_time = format_datetime(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6]) # Inputs 1 - 6
	earliest_start_time = format_datetime(sys.argv[7], sys.argv[8], sys.argv[9], sys.argv[10], sys.argv[11], sys.argv[12]) # Inputs 7 - 12
	latest_start_time = format_datetime(sys.argv[13], sys.argv[14], sys.argv[15], sys.argv[16], sys.argv[17], sys.argv[18]) # Inputs 13 - 18

	duration = format_duration(sys.argv[19], sys.argv[20], sys.argv[21], sys.argv[22]) # Inputs 19 - 22

	ptr_id = sys.argv[23] # Input 23

	priority = str(0) 
	priority = sys.argv[24] # Input 24

	explan_text = ""
	explan_text = sys.argv[25].split() # Input 25


	# Generate XML file from inputted data

	xml = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
	<ptrFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PtrFile.xsd">
		<fileHeader>
			<source>?</source>	
			<destination>MPS</destination>	
			<issueDate></issueDate>		
			<information>Generated by ?</information>			
		</fileHeader>
		<ptrFileId>"""+str(ptr_id)+"""</ptrFileId>	
			<ptr>
			<domain>TDS-1</domain>
			<ptrId>"""+str(ptr_id)+"""</ptrId>
			<preferredStartTime>"""+pref_start_time+"""</preferredStartTime>
			<earliestStartTime>"""+earliest_start_time+"""</earliestStartTime>
			<latestStartTime>"""+latest_start_time+"""</latestStartTime>
			<duration>"""+duration+"""</duration>
			<taskPriority>"""+priority+"""</taskPriority>
			<explanatoryText>"""+explan_text+"""</explanatoryText>
			<TASK_LUCID_DATA/>	
		</ptr>
	</ptrFile>

	"""

	# Output XML to 'output.PTR' so data be read by PHP

	#outfile = open("output.ptr", "w")
	#outfile.write(xml)
	#outfile.close()
        print xml
	#print "\nDone"
	
